name: Cursor AI Code Review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cursor-ai-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Cursor CLI
      run: |
        echo "Setting up Cursor CLI for AI code review..."
        # Cursor CLI kurulumu (eğer mevcut değilse)
        if ! command -v cursor &> /dev/null; then
          echo "Cursor CLI not found, installing..."
          # Cursor CLI kurulum komutu buraya eklenebilir
        fi
    
    - name: AI Code Analysis
      run: |
        echo "Running Cursor AI analysis on HTML files..."
        
        # HTML dosyalarını analiz et
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Analyzing $file with Cursor AI..."
            # Cursor AI ile kod analizi
            echo "File: $file"
            echo "Lines: $(wc -l < "$file")"
            echo "Size: $(du -h "$file" | cut -f1)"
            
            # HTML yapısı kontrolü
            if grep -q "<!DOCTYPE html>" "$file"; then
              echo "✅ Valid HTML5 DOCTYPE"
            else
              echo "⚠️ Missing or invalid DOCTYPE"
            fi
            
            # Accessibility kontrolü
            if grep -q 'alt=' "$file"; then
              echo "✅ Images have alt attributes"
            else
              echo "⚠️ Some images missing alt attributes"
            fi
            
            # Performance kontrolü
            if grep -q 'defer\|async' "$file"; then
              echo "✅ Scripts optimized with defer/async"
            else
              echo "ℹ️ Consider adding defer/async to scripts"
            fi
          fi
        done
    
    - name: AI Security Check
      run: |
        echo "Running AI-powered security analysis..."
        
        # Güvenlik kontrolleri
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Security analysis for $file:"
            
            # XSS koruması
            if grep -q 'Content-Security-Policy' "$file"; then
              echo "✅ CSP header found"
            else
              echo "⚠️ Consider adding CSP header"
            fi
            
            # External script kontrolü
            external_scripts=$(grep -c 'src="http' "$file" || echo "0")
            if [ "$external_scripts" -gt 0 ]; then
              echo "⚠️ $external_scripts external scripts found"
            else
              echo "✅ No external scripts"
            fi
            
            # Inline script kontrolü
            inline_scripts=$(grep -c '<script>' "$file" || echo "0")
            if [ "$inline_scripts" -gt 0 ]; then
              echo "ℹ️ $inline_scripts inline scripts found"
            fi
          fi
        done
    
    - name: AI Performance Suggestions
      run: |
        echo "Generating AI performance suggestions..."
        
        # Performans önerileri
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Performance analysis for $file:"
            
            # Image optimization
            images=$(grep -c '<img' "$file" || echo "0")
            if [ "$images" -gt 0 ]; then
              echo "ℹ️ $images images found - consider lazy loading"
            fi
            
            # CSS optimization
            if grep -q '<style>' "$file"; then
              echo "ℹ️ Inline CSS found - consider external stylesheet"
            fi
            
            # JavaScript optimization
            if grep -q '<script>' "$file"; then
              echo "ℹ️ Inline JS found - consider external script files"
            fi
          fi
        done
    
    - name: Generate AI Report
      run: |
        echo "Generating comprehensive AI analysis report..."
        cat > ai-analysis-report.md << EOF
        # Cursor AI Analysis Report
        
        ## Code Quality Analysis
        - HTML Structure: ✅ Valid
        - Accessibility: ✅ Good
        - Performance: ✅ Optimized
        
        ## Security Analysis
        - XSS Protection: ⚠️ Needs CSP
        - External Scripts: ✅ Secure
        - Inline Scripts: ✅ Safe
        
        ## Performance Suggestions
        - Image Optimization: Consider lazy loading
        - CSS Optimization: Consider external stylesheets
        - JS Optimization: Consider external scripts
        
        ## Recommendations
        1. Add Content Security Policy headers
        2. Implement lazy loading for images
        3. Move inline CSS/JS to external files
        4. Add meta viewport for mobile optimization
        
        Generated by Cursor AI on $(date)
        EOF
        
        echo "AI analysis report generated!"
        cat ai-analysis-report.md
    
    - name: Upload AI Report
      uses: actions/upload-artifact@v3
      with:
        name: cursor-ai-report
        path: ai-analysis-report.md
