name: Website Health Check

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check website availability
      run: |
        echo "Testing website: https://tlgselvi.github.io/poolsfilters"
        response=$(curl -s -o /dev/null -w "%{http_code}" https://tlgselvi.github.io/poolsfilters)
        echo "HTTP Status: $response"
        if [ "$response" -eq 200 ]; then
          echo "✅ Website is accessible"
        else
          echo "❌ Website is not accessible - Status: $response"
          exit 1
        fi
    
    - name: Check for broken links
      run: |
        echo "Checking for broken links..."
        # Ana sayfa linklerini kontrol et
        curl -s https://tlgselvi.github.io/poolsfilters | grep -o 'href="[^"]*"' | while read link; do
          url=$(echo $link | sed 's/href="//;s/"//')
          if [[ $url == http* ]]; then
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            if [ "$status" -ne 200 ]; then
              echo "❌ Broken link: $url (Status: $status)"
            else
              echo "✅ Working link: $url"
            fi
          fi
        done
    
    - name: Check page load time
      run: |
        echo "Checking page load time..."
        time curl -s -o /dev/null -w "Total time: %{time_total}s\n" https://tlgselvi.github.io/poolsfilters
    
    - name: Check for JavaScript errors
      run: |
        echo "Checking for JavaScript errors..."
        # Basit JS syntax kontrolü
        if [ -f "index.html" ]; then
          if grep -q "<script>" index.html; then
            echo "✅ JavaScript found in HTML"
          else
            echo "ℹ️ No JavaScript found"
          fi
        fi
